export const lyricsData = [
  { time: 0, text: " " },
  { time: 0.5, text: "Trails of smoke trapped in a two by two" },
  { time: 5, text: "Wasting the night" },
  { time: 8, text: "feels right when I’m with you." },
  { time: 12, text: "It’s the shimmer in your eyes" },
  { time: 18, text: "and the way you let down your disguise." },
  { time: 23, text: ". . ." },
  { time: 25, text: "I feel like I’ve known you for ages." },
  { time: 36, text: "I feel like with you I’m going places." },
  { time: 46, text: ". . ." },
  { time: 53, text: "The same song on repeat" },
  { time: 58, text: "“You can call me anything you want”" },
  { time: 65, text: "It’s fine by me" },
  { time: 70, text: "Number two out of three." },
  { time: 76, text: "He says that it’s his favourite" },
  { time: 81, text: "and I can’t disagree." },
  { time: 86, text: ". . ." },
  { time: 103, text: "We talk about everything" },
  { time: 107, text: "the important and the mundane." },
  { time: 112, text: "You know I think you know everything." },
  { time: 117, text: "But the night’s still young" },
  { time: 120, text: "and there’s still so much to gain." },
  { time: 124, text: "I feel like I’ve known you for ages." },
  { time: 135, text: "I feel like with you I’m going places." },
  { time: 146, text: ". . ." },
  { time: 152, text: "The same song on repeat" },
  { time: 157, text: "“You can call me anything you want”" },
  { time: 163, text: "It’s fine by me" },
  { time: 168, text: "Number two out of three." },
  { time: 175, text: "He says that it’s his favourite" },
  { time: 180, text: "and I can’t disagree." },
  { time: 185, text: "The same song on repeat" },
  { time: 190, text: "“You can call me anything you want”" },
  { time: 196, text: "It’s fine by me" },
  { time: 201, text: "Number two out of three." },
  { time: 207, text: "He says that it’s his favourite" },
  { time: 212, text: "and I can’t disagree." },
  { time: 217, text: ". . ." },
];
